TestMVC45/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TestMVC45.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestMVC45/Controllers/MaintainController.cs
using System.Web.Mvc;
using eAMS.BusinessNew.DbInteract;
using eAMS.Models.Models;

namespace TestMVC45.Controllers
{
    public class MaintainController : Controller
    {
        public ViewResult Index()
        {
            var list = new MaintainancesInteractor().ListMaintainActions();

            return View(list);
        }

        public JsonResult GetListMaintainance()
        {
            var list = new MaintainancesInteractor().ListMaintainActions();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveAction(PropMaint propMaint)
        {
            var checkString = new MaintainancesInteractor().SaveChanges(propMaint);
            return Json(checkString, JsonRequestBehavior.AllowGet);
        }
    }
}

TestMVC45/Controllers/PropertyController.cs
using eAMS.BusinessNew.DbInteract;
using eAMS.BusinessNew.Helper;
using eAMS.Models.Models;
using Newtonsoft.Json;
using System;
using System.Web.Mvc;
using TestMVC45.Controllers.Helper;
using ClosedXML.Excel;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;

namespace TestMVC45.Controllers
{
    public class PropertyController : Controller
    {
        const string SUCCESSFUL = "Successful";
        const string ERROR = "Error";

        public ViewResult Index()
        {
            return View();
        }

        public JsonResult GetPropertyList(int pageNumber = 1, int pageSize = 5)
        {
            var list = new RegisterInteractor().ListProperty();
            var pagedData = Pagination.PageResult(list, pageNumber, pageSize);
            return Json(pagedData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPropertyById(int propertyId)
        {
            bool SafetyCheck = new DataValidation().CheckPropertyId(propertyId);
            if (SafetyCheck)
            {
                var res = new RegisterInteractor().ListPropertyById(propertyId);
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            return Json(ERROR, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteProperty(int propertyId)
        {
            bool SafetyCheck = new DataValidation().CheckPropertyId(propertyId);
            if (SafetyCheck)
            {
                string checkString = new RegisterInteractor().RemoveProperty(propertyId);
                return Json(checkString, JsonRequestBehavior.AllowGet);
            }
            return Json(ERROR, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SavePropertyToDb(int propertyId, string propertyCode, string propertyName, string propertyBrand, string propertyYear, bool propertyIsMaintained, int? propertyMCost)
        {
            PropRegi property = new PropRegi
            {
                ID = propertyId,
                Code = propertyCode,
                Name = propertyName,
                Brand = propertyBrand,
                Year = propertyYear,
                IsMaitained = propertyIsMaintained,
                MCost = propertyMCost
            };
            bool SafetyCheck = new DataValidation().Check(property);

            if (SafetyCheck)
            {
                string checkString = new RegisterInteractor().SaveProperty(property);
                return Json(checkString, JsonRequestBehavior.AllowGet);
            } else
            {
                return Json(ERROR, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult SearchPropety(string searchString, string searchBy)
        {
            var searchResult = new RegisterInteractor().SearchProperty(searchString, searchBy);
            return Json(searchResult, JsonRequestBehavior.AllowGet);
        }

        /*
         * @Mixin means Property and Maintain
         * Only show which has IsMaintained
         * @params: propertyNeed is only for safety checked
         */
        public ContentResult GetMixin(int propertyId, bool propertyNeed = true)
        {
            bool SafetyCheck = new DataValidation().CheckPropertyId(propertyId);
            if (propertyNeed && SafetyCheck)
            {
                var list = new RegisterInteractor().ListMixin(propertyId);
                var lol = JsonConvert.SerializeObject(list,
                    Formatting.None,
                    new JsonSerializerSettings() {
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                    });

                return Content(lol, "application/json");
            }
            return Content(ERROR);
        }

        public JsonResult GetPropertyByCode(string propertyCode)
        {
            bool SafetyCheck = new DataValidation().CheckRequired(propertyCode);
            if (SafetyCheck)
            {
                var list = new RegisterInteractor().FindPropertyByCode(propertyCode);
                if (list != null)
                {
                    return Json(list, JsonRequestBehavior.AllowGet);
                }
                return Json(ERROR, JsonRequestBehavior.AllowGet);
            }
            return Json(ERROR, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExportToExcel()
        {
            var list = new RegisterInteractor().ListProperty();
            var gv = new GridView
            {
                DataSource = list
            };
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }
    }
}

TestMVC45/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestMVC45/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestMVC45/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestMVC45/Views/Maintain/Index.cshtml
@model IEnumerable<eAMS.Models.Models.PropMaint>
@{
    Layout = "~/Views/Shared/_PropertyLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/PropertyTheme/maintain-search.css" />

<div class="container" style="margin-top:3%">
    <a href="#" class="btn btn-info" onclick="AddNewAction()">Add New Action</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Property Code</th>
                <th>Action Done</th>
                <th>Date Done</th>
                <th>Reality Cost</th>
            </tr>
        </thead>
        <tbody id="">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Action)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PropRegi.Name)
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="modal fade" id="AlterModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="AlterModal-Title"></h4>
                </div>
                <div class="modal-body">
                    <form id="form" class="col-sm-offset-3">
                        <fieldset id="SubmitForm">
                            <input name="ID" id="ActionID" type="text" hidden />
                            <div class="form-group autocomplete">
                                <label for="Code">Property Code:</label>
                                <input name="Code" id="PropCode" 
                                       type="text" class="form-control" 
                                       placeholder="To find the original" onkeyup="FindPropertyCode()"/>
                            </div>
                            <div class="form-group">
                                <label for="Action">Action Done:</label>
                                <input name="Action" id="MainAction" type="text" class="form-control" placeholder="What did you do?" />
                            </div>
                            <div class="form-group">
                                <label for="Date">Date Done:</label>
                                <input name="Date" id="MainDate" type="date" class="form-control" placeholder="When did you do that?" />
                            </div>
                            <div class="form-group">
                                <label for="RCost">Reality Cost:</label>
                                <input name="RCost" id="MainRCost" type="number" class="form-control" placeholder="How much did you pay for real?" />
                            </div>
                        </fieldset>
                    </form>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal">Close</a>
                    <a class="btn btn-danger" id="SaveAction">Save Changes</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>

    function DataBinding(DataList) {
        const SetMaintainData = $("#SetMaintainData");

        SetMaintainData.empty();
        for (let i = 0; i < DataList.length; i++) {
            const Data = `<tr class="row_${DataList[i].ID}">
                <td>${DataList[i].Code}</td>
                <td>${DataList[i].Action}</td>
                <td>${DataList[i].Date}</td>
                <td>${DataList[i].RCost}</td>
                <td>${DataList[i].PropRegi.Name}</td>
                <td><a class="btn btn-info" onclick="EditProperty(${DataList[i].ID})">Edit</a></td>
                </tr>`;
            SetMaintainData.append(Data);
        }
    }

    function AddNewAction() {
        $("#form")[0].reset();
        $("#ActionID").val(0);
        $("#AlterModal-Title").html("Add New Property");
        $("#AlterModal").modal("show");
    }

    $("#SaveAction").click(() => {
        const data = $("#SubmitForm").serialize();
        const url = "/Maintain/SaveAction";

        $.ajax({
            type: "POST",
            url: url,
            data: data,
            success: (data) => {
                window.location.href = "/Maintain/Index";
                $("#AlterModal").modal("hide");
            },
            error: (err) => {
                console.log(err);
            }
        });
    });

    function FindPropertyCode() {
        const PropCode = $("#PropCode").val().trim();
        const url = `/Property/GetPropertyByCode?PropertyCode=${PropCode}`;

        $.ajax({
            type: "GET",
            url: url,
            data: {
                propertyCode: PropCode
            },
            success: (data) => {
                console.log(data)
                if (data === "Error") {
                    alert("You cannot pass unknown, that's unelegant")
                } else {
                    //GetData
                    const inp = $("#PropCode");
                    let arr = [];
                    for (let i = 0; i < data.length; i++) {
                        arr.push(data[i].Code);
                    }
                    autocomplete(document.getElementById("PropCode"), arr);
                }
            },
            error: (err) => {
                console.log(err);
            }
        });
    }

    function autocomplete(inp, arr) {
        /*the autocomplete function takes two arguments,
        the text field element and an array of possible autocompleted values:*/
        var currentFocus;
        /*execute a function when someone writes in the text field:*/
        inp.addEventListener("input", function (e) {
            var a, b, i, val = this.value;
            /*close any already open lists of autocompleted values*/
            closeAllLists();
            if (!val) { return false; }
            currentFocus = -1;
            /*create a DIV element that will contain the items (values):*/
            a = document.createElement("DIV");
            a.setAttribute("id", this.id + "autocomplete-list");
            a.setAttribute("class", "autocomplete-items");
            /*append the DIV element as a child of the autocomplete container:*/
            this.parentNode.appendChild(a);
            /*for each item in the array...*/
            for (i = 0; i < arr.length; i++) {
                /*check if the item starts with the same letters as the text field value:*/
                if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                    /*create a DIV element for each matching element:*/
                    b = document.createElement("DIV");
                    /*make the matching letters bold:*/
                    b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                    b.innerHTML += arr[i].substr(val.length);
                    /*insert a input field that will hold the current array item's value:*/
                    b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
                    /*execute a function when someone clicks on the item value (DIV element):*/
                    b.addEventListener("click", function (e) {
                        /*insert the value for the autocomplete text field:*/
                        inp.value = this.getElementsByTagName("input")[0].value;
                        /*close the list of autocompleted values,
                        (or any other open lists of autocompleted values:*/
                        closeAllLists();
                    });
                    a.appendChild(b);
                }
            }
        });
        /*execute a function presses a key on the keyboard:*/
        inp.addEventListener("keydown", function (e) {
            var x = document.getElementById(this.id + "autocomplete-list");
            if (x) x = x.getElementsByTagName("div");
            if (e.keyCode == 40) {
                /*If the arrow DOWN key is pressed,
                increase the currentFocus variable:*/
                currentFocus++;
                /*and and make the current item more visible:*/
                addActive(x);
            } else if (e.keyCode == 38) { //up
                /*If the arrow UP key is pressed,
                decrease the currentFocus variable:*/
                currentFocus--;
                /*and and make the current item more visible:*/
                addActive(x);
            } else if (e.keyCode == 13) {
                /*If the ENTER key is pressed, prevent the form from being submitted,*/
                e.preventDefault();
                if (currentFocus > -1) {
                    /*and simulate a click on the "active" item:*/
                    if (x) x[currentFocus].click();
                }
            }
        });
        function addActive(x) {
            /*a function to classify an item as "active":*/
            if (!x) return false;
            console.log(x);
            /*start by removing the "active" class on all items:*/
            removeActive(x);
            if (currentFocus >= x.length) currentFocus = 0;
            if (currentFocus < 0) currentFocus = (x.length - 1);
            /*add class "autocomplete-active":*/
            x[currentFocus].classList.add("autocomplete-active");
        }
        function removeActive(x) {
            /*a function to remove the "active" class from all autocomplete items:*/
            for (var i = 0; i < x.length; i++) {
                x[i].classList.remove("autocomplete-active");
            }
        }
        function closeAllLists(elmnt) {
            /*close all autocomplete lists in the document,
            except the one passed as an argument:*/
            var x = document.getElementsByClassName("autocomplete-items");
            for (var i = 0; i < x.length; i++) {
                if (elmnt != x[i] && elmnt != inp) {
                    x[i].parentNode.removeChild(x[i]);
                }
            }
        }
        /*execute a function when someone clicks in the document:*/
        document.addEventListener("click", function (e) {
            closeAllLists(e.target);
        });
    }
</script>

TestMVC45/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestMVC45/Views/Shared/_PropertyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/PropertyTheme/layout.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="container-fluid body-content wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Property Control</h3>
                <strong>PC</strong>
            </div>

            <ul class="list-unstyled components">
                <li class="active">
                    @*@Html.ActionLink("<i class=\"fas fa-home\"></i> Home", "Index", "Property")*@
                    <a href="/Property/Index">
                        <i class="fas fa-home"></i>
                        Home
                    </a>
                    @*<ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>*@
                </li>
                <li>
                    <a href="/Maintain/Index">
                        <i class="fas fa-briefcase"></i>
                        Maintainance Actions
                    </a>
                    @*<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        Pages
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>*@
                </li>
            </ul>

        </nav>
        <div id="content">
            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
            @RenderBody()
        </div>
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

        });
    </script>
</body>
</html>